API/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('auth/', views.login),
    path('students/', views.getAllStudent),
    path('student/<str:id>', views.getStudent, name='student'),
    #     path('address/', views.getAddress, name='address'),
    #     path('devices/', views.getDevice, name='devices'),
    path('meal/', views.getMeal, name='meal'),
    #     path('cafe_attendance/', views.getCafeAttendance, name='cafe_attendance'),
    path('cafe_attendance/',
         views.getCafeAttendance, name='cafe_attendance_update'),
    path('add_disciplinary_record/', views.createDisciplinaryRecord,
         name='add_disciplinary_record'),

]

ID_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('university.urls', namespace='university')),
    path('api/', include('API.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

university/urls.py
from django.urls import path
from . import views

app_name = 'university'
urlpatterns = [
     path('', views.index, name='home'),
     path('about/', views.about_us, name='about_us'),
     path('staff/password/', views.ChangePasswordView.as_view(), name='password_change'),
     path('staff/<int:pk>', views.staff_update, name='staff_update'),
     path('staffs/registor/', views.create_staff, name='register-staff'),
     path('view_card/', views.view_scan, name='view-card'),
     path('view_card/<str:student_id>/', views.view_card, name='view-id'),
     path('login/', views.loginPage, name='login'),
     path("logout/", views.LogoutView.as_view(), name="logout"),


     # Student registration and QR code generation module
     path('student/registor/', views.student_form, name='register-student'),
     path('students/', views.students_list, name='list-students'),
     path('student_profile/<str:student_id>',
          views.student_profile, name='student-profile'),
     path('student_profile/update/<str:student_id>',
          views.update_student_profile, name='student-profile-update'),
     path('student_profile/add_device/<str:student_id>',
          views.add_device, name='add-device'),
     path('staffs/add/uni_info/', views.university_form,
          name='add-university-info'),
     path('staffs/list/uni_info/', views.department_list,
          name='department-list'),


     # Cafeteria service module
     path('cafe/', views.cafe_maneger, name='cafe-manager'),
     path('cafe/form/', views.cafe_form, name='cafe-form'),
     path('cafe/eat/<str:pk>', views.eat_meal, name='eat-meal'),
     path('cafe/coupon/add/', views.add_coupon, name='add-coupon'),
     path('cafe/coupon/list/', views.CouponListView.as_view(), name='list-coupon'),
     path('cafe/coupon/<int:coupon_id>/',
          views.coupon_detail, name='coupon-detail'),
     path('cafe/coupon/delete/<int:coupon_id>/',
          views.CouponDeleteView.as_view(), name='delete-coupon'),
     path('cafe/add_coupon_to_students/', views.add_coupon_to_students,
          name='add-coupon-to-students'),
     path('cafe/student/detail/<str:student_id>/', views.cafe_user_detail,
          name='cafe-student-detail'),


     # Library module
     path('library/', views.LibraryListView.as_view(), name='library-manager'),
     path('library/<int:pk>/return/', views.book_return, name='library-return'),
     path('library/add_book/', views.add_book, name='add-book'),
     path('library/students/', views.library_student_list,
          name='student-book-rent'),
     path('library/book-rental/<str:student_id>/',
          views.book_rental_page, name='book-rental-page'),
     path('library/book-rental/<str:student_id>/<int:book_id>/rent/',
          views.rent_book, name='rent-book'),

     # Disciplinary recording module
     path('disciplin/',
          views.DisStudentListView.as_view(), name='disciplin-student-list'),
     path('disciplin/record/<str:student_id>/',
          views.add_disciplinary_record, name='disciplin-form'),
     path('disciplin/list/<str:student_id>/',
          views.disciplinary_records, name='disciplin-list'),
     path('disciplin/recored/<int:record_id>/',
          views.disciplinary_record, name='disciplin-recored-detail'),


]

university/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.core import validators
import uuid
import qrcode
import datetime

from .utils import generate_qr_code
from .validators import *


def get_student_photo_filepath(self, image):
    return f"students/{self.full_name}/photo/{self.full_name}.png"


def get_default_photo():
    return "profile_images/default_profile_pic.png"


def get_student_qr_code_filepath(self, image):
    return f"student/{self.full_name}/qr_code/{self.full_name}.png"


def get_profile_image_filepath(self, image):
    return f"staffs/{self.username}/profile_images/{self.username}_profile_image.png"


def get_default_profile_image():
    return "profile_images/default_profile_pic.png"


class Staff(AbstractUser):
    ROLE = (
        ("REGISTRAR", "Registrar"),
        ("LIBRARIAN", "Librarian"),
        ("PROCTOR", "Proctor"),
        ("SECURITY", "Security"),
        ("CAFE_STAFF", "Cafe Staff"),
        ("ADMIN", "Admin"),
    )
    full_name_am = models.CharField(
        "ሙሉ ስም", max_length=200, validators=[validate_amharic], null=True, blank=True
    )
    phone_number = models.CharField(
        max_length=20,
        validators=[validate_ethiopian_phone_number],
        null=True,
        blank=True,
    )
    photo = models.ImageField(
        "profile picture",
        upload_to=get_profile_image_filepath,
        default=get_default_profile_image,
        blank=True,
    )
    email = models.EmailField("email address", unique=True, null=True, blank=True)
    role = models.CharField("Role", max_length=10, choices=ROLE)


    # def get_absolute_url(self):
    #     return reverse("staff_detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        if self.pk is None and self.is_superuser:
            self.role = "ADMIN"
        if self.role in ("ADMIN", "REGISTRAR"):
            self.is_superuser = True
        if self.role not in ("ADMIN", "REGISTRAR"):
            self.is_superuser = False
        if self.photo is None:
            self.photo = get_default_photo

        super().save(*args, **kwargs)


User = get_user_model()


class Address(models.Model):
    telephone_phone = models.CharField(max_length=20, validators=[
                                       validate_ethiopian_phone_number], null=True, blank=True)
    email = models.EmailField()
    country = models.CharField(max_length=150)
    region = models.CharField(max_length=150)
    state = models.CharField(max_length=150)

    def __str__(self):
        return self.country + ', ' + self.region + ', ' + self.state


class EmergencyContact(models.Model):
    name = models.CharField(max_length=255, verbose_name="Full Name")
    name_am = models.CharField(
        max_length=255, verbose_name="ሙሉ ስም", validators=[validate_amharic])
    relationship = models.CharField(
        max_length=255, verbose_name="relationship")
    relationship_am = models.CharField(
        max_length=255, verbose_name="ዝምድና", validators=[validate_amharic])
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    country = models.CharField(max_length=150, null=True, blank=True)
    region = models.CharField(max_length=150, null=True, blank=True)
    state = models.CharField(max_length=150, null=True, blank=True)

    def __str__(self):
        return self.name

    def address(self):
        return self.country + ', ' + self.region + ', ' + self.state


class Coupon(models.Model):
    coupon_type = models.CharField(max_length=50)
    discription = models.TextField(max_length=100, null=True, blank=True)
    expiration_date = models.DateField(validators=[validators.MinValueValidator(
        limit_value=datetime.datetime.today().date(), message="Expiration date cannot be earlier than today's date.")])

    def __str__(self):
        return f"{self.coupon_type} - {self.expiration_date}"


class Campus(models.Model):
    name = models.CharField(max_length=255, verbose_name='Campus Name')
    name_am = models.CharField(
        max_length=255, verbose_name='የካምፓስ ስም', validators=[validate_amharic])
    address = models.ForeignKey(Address, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Field(models.Model):
    name = models.CharField(max_length=255, verbose_name='Field Name')
    name_am = models.CharField(
        max_length=255, verbose_name='ፊልድ', validators=[validate_amharic])
    campus = models.ForeignKey(Campus, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Department(models.Model):
    name = models.CharField(max_length=255, verbose_name='Department Name')
    name_am = models.CharField(
        max_length=255, verbose_name='የትምህርት ክፍል', validators=[validate_amharic])
    field = models.ForeignKey(Field, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Student(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    # Fields for student information
    first_name = models.CharField(max_length=100, verbose_name='First Name')
    first_name_am = models.CharField(
        max_length=100, verbose_name='ስም', validators=[validate_amharic])
    last_name = models.CharField(max_length=100, verbose_name='Last Name')
    last_name_am = models.CharField(
        max_length=100, verbose_name='የአባት ስም', validators=[validate_amharic])
    student_id = models.CharField(max_length=20, unique=True)
    photo = models.ImageField(upload_to='photos/', default='img/p_pic.png')
    qr_code = models.ImageField(upload_to='qr_codes')
    date_of_birth = models.DateField(validators=[validate_birth_date])
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    government_id_number = models.CharField(max_length=50)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    emergency = models.ForeignKey(
        EmergencyContact, on_delete=models.CASCADE)
    registration_date = models.DateTimeField(auto_now_add=True)
    address = models.ForeignKey(
        Address, on_delete=models.CASCADE, default=None, null=True, blank=True)
    financial_aid = models.BooleanField()
    is_cafe_user = models.BooleanField(default=True)
    is_student_associative = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    coupon = models.ManyToManyField(
        Coupon, verbose_name="coupon", blank=True,  related_name='students')
    year = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.student_id})"

    def age(self):
        today = datetime.date.today()
        return today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def save(self, *args, **kwargs):
        # Generate unique student ID and QR code when student is registered
        if not self.pk:

            # Generate UUID
            unique_id = uuid.uuid4().hex[:5].upper()

            # Get 2 digites of year
            current_year = datetime.datetime.now().year
            last_two_digits = current_year % 100
            year = str(last_two_digits)[-2:]

            # Set student ID in the format "UoG/XXXXX/year"
            self.student_id = f"UoG|{unique_id}|{year}"

            if not self.qr_code:
                self.qr_code = generate_qr_code(self.student_id)
        super().save(*args, **kwargs)


class Device(models.Model):
    student = models.ForeignKey(
        Student, on_delete=models.CASCADE, related_name='devices')
    device_type = models.CharField(max_length=80)
    device_model = models.CharField(max_length=100)
    serial_number = models.CharField(max_length=17)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.serial_number} ({self.student})"


class SpecialMealPeriod(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Meal(models.Model):
    MEAL_PERIODS = (
        ('breakfast', 'Breakfast'),
        ('lunch', 'Lunch'),
        ('dinner', 'Dinner'),
        # Add special meal periods from the SpecialMealPeriod model
        *[(special_meal_period.name.lower(), special_meal_period.name.title()) for special_meal_period in SpecialMealPeriod.objects.all()]
    )

    meal_period = models.CharField(choices=MEAL_PERIODS, max_length=20)
    start_time = models.TimeField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return f'{self.get_meal_period_display()} - From {self.start_date} to {self.end_date}'.format(self.start_date, self.end_date)

    def time(self):
        return f'From {self.start_date} to {self.end_date}'.format(self.start_date, self.end_date)


class CafeAttendance(models.Model):
    student = models.ForeignKey(
        Student, on_delete=models.CASCADE, related_name='cafeatendance_set')
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    has_eaten = models.BooleanField(default=False)
    check_in_time = models.TimeField(null=True, blank=True)

    def __str__(self):
        return f'{self.student} - {self.meal} - {self.has_eaten}'

    def save(self, *args, **kwargs):
        if self.has_eaten:
            self.check_in_time = datetime.datetime.now().time()
        super().save(*args, **kwargs)


class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    isbn = models.CharField(max_length=13)

    def __str__(self):
        return f'{self.title} - {self.author}'


class Library(models.Model):

university/templates/university/cafe/add_coupon.html
{% extends 'base/base.html' %}

{% block title %}Cafe Form{% endblock %}

{% block content %}
{% include 'base/header.html' with active_tab='cafe' %}

{% include 'base/side_bar.html' with active_tab='cafe' %}

{% load crispy_forms_tags %}


  <div class="container-sm my-3 py-3">
    <div class="row" id="main">
      <p>Create Coupon</p>
      <form method="POST" action=''>
        {% csrf_token %}
        {{ coupon_form|crispy }}
        <div class="d-md-flex justify-content-md-end">
          <button name="coupon_submit" type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form> 
    </div>
  </div>  


{% include 'base/footer.html' %}

{% endblock %}

university/templates/university/cafe/add_coupon_to_students.html
{% extends 'base/base.html' %}
{% block title %}Cafe Form{% endblock %}

{% block content %}
{% include 'base/header.html' with active_tab='cafe' %}
{% include 'base/side_bar.html' with active_tab='cafe' %}

{% load crispy_forms_tags %}

<div class="container">
  <div class="row" id="main">
      <h1>Add Coupon to Students</h1>
      <form method="post">
          {% csrf_token %}

          <div class="list-group dual-listbox-container m-3">
            <div class="list-group-item active">
              <h5 class="list-group-item-heading">Available Coupon</h5>
              <input type="text" class="form-control search-input" placeholder="Search...">
            </div>
              <select name="coupons[]" id="coupons" multiple class="form-control">
                  {% for coupon in coupons %}
                      <option value="{{ coupon.id }}">{{ coupon.coupon_type }}</option>
                  {% endfor %}
              </select>
          </div>

          <div class="list-group dual-listbox-container m-3">
            <div class="list-group-item active">
              <h5 class="list-group-item-heading">Students</h5>
              <input type="text" class="form-control search-input" placeholder="Search...">
            </div>
            <select name="students[]" id="students" multiple class="form-control">
                {% for student in students %}
                  <option value="{{ student.id }}" data-first-name="{{ student.first_name }}" data-last-name="{{ student.last_name }}" data-student-id="{{ student.student_id }}">{{ student.first_name }} {{ student.last_name }}</option>
                {% endfor %}
            </select>
          </div>

          <button name="student_coupon_submit" class="btn btn-primary" type="submit">Add Coupon to Selected Students</button>
      </form>
  </div>
</div>

{% block javascripts %}

  <script>
    var students = document.getElementById('students');
    var coupons = document.getElementById('coupons');
    var searchInputs = document.querySelectorAll('.search-input');

    searchInputs.forEach(function(searchInput) {
      searchInput.addEventListener('input', function() {
        filterOptions(this, this.parentNode.nextElementSibling);
      });
    });

    function filterOptions(searchInput, selectBox) {
      var options = selectBox.getElementsByTagName('option');
      var searchText = searchInput.value.toLowerCase();

      for (var i = 0; i < options.length; i++) {
        var optionText = options[i].text.toLowerCase();
        var optionFirstName = options[i].getAttribute('data-first-name').toLowerCase();
        var optionLastName = options[i].getAttribute('data-last-name').toLowerCase();
        var optionStudentId = options[i].getAttribute('data-student-id');

        if (optionText.includes(searchText) || optionFirstName.includes(searchText) || optionLastName.includes(searchText) || optionStudentId.includes(searchText)) {
          options[i].style.display = '';
        } else {
          options[i].style.display = 'none';
        }
      }
    }

  </script>

{% endblock javascripts %}

{% include 'base/footer.html' %}
{% endblock %}

university/templates/university/cafe/admin.html
{% extends 'base/base.html' %}

{% block title %}Cafe Admin{% endblock %}

{% block content %}
{% include 'base/header.html' with active_tab='cafe' %}

{% include 'base/side_bar.html' with active_tab='cafe' %}

<div class="container" id="main">
  <div class="d-none d-md-block">

    {% include 'university/cafe/dashboard.html' %}
  </div>

 <div class="my-3">
  {% include 'university/cafe/student_list.html' %}
 </div> 
  {% include 'university/cafe/coupon.html' %}

</div>

{% include 'base/footer.html' with active_tab='home' %}

{% endblock %}

university/templates/university/cafe/cafe_user_detail.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Cafe Form{% endblock %}

{% block content %}
{% include 'base/header.html' with active_tab='cafe' %}
{% include 'base/side_bar.html' with active_tab='cafe' %}

<div class="container my-3" id="main">
  <a href="{% url 'university:cafe-manager' %}" class="btn btn-primary"><i class="fas fa-home"></i> Cafe Dashboard</a>
  <h1>{{ student.first_name }} {{ student.last_name }}</h1>
  <div class="row">
    <div class="col-md-6">
      <img src="{{ student.photo.url }}" alt="{{ student.first_name }} {{ student.last_name }}" class="img-fluid">
      <p>{{ student.email }}</p>
      <p>{{ student.phone }}</p>
      <p>{{ student.address }}</p>
    </div>
    <div class="col-md-6">
      <dl class="row">
        <dt class="col-sm-3">ID</dt>
        <dd class="col-sm-9">{{ student.student_id }}</dd>
        <dt class="col-sm-3">Date of Birth</dt>
        <dd class="col-sm-9">{{ student.date_of_birth }}</dd>
        <dt class="col-sm-3">Gender</dt>
        <dd class="col-sm-9">{{ student.get_gender_display }}</dd>
        <dt class="col-sm-3">Department</dt>
        <dd class="col-sm-9">{{ student.department }}</dd>
        <dt class="col-sm-3">Field</dt>
        <dd class="col-sm-9">{{ student.field }}</dd>
        <dt class="col-sm-3">Cafe User</dt>
        <dd class="col-sm-9">{% if student.is_cafe_user %}Yes{% else %}No{% endif %}</dd>
        <dt class="col-sm-3">Financial Aid</dt>
        <dd class="col-sm-9">{% if student.financial_aid %}Yes{% else %}No{% endif %}</dd>
        <dt class="col-sm-3"></dt>
        <dd class="col-sm-9">{% if student.is_student_associative %}Student Association Member{% else %}{% endif %}</dd>
      </dl>
      <a href="{% url 'university:disciplin-form' student.student_id %}" class="btn btn-danger text-black">Add Discipline Recored</a>
    </div>
  </div>

  <div class="row">
    
    <div class="col-md-4">
      <h5>{{ student }} Attendance</h5>
      <canvas id="attendanceChart"></canvas>
    </div>

    <div class="col-md-8">
      {% if disciplinary_record %}
      
        <h5>Disciplinary Records from Cafe Staff</h5>

        {% for disciplinary_record in disciplinary_records %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ disciplinary_record.date }}</h5>
                    <p class="card-text">{{ disciplinary_record.reason }}</p>
                    <p class="card-text">Recored added by: {{ disciplinary_record.staff__first_name }} {{ disciplinary_record.staff__last_name }}</p>
                </div>
            </div>
        {% endfor %}
      {% else %}
            <h5>No Disciplinary Recordes in Cafe</h5>
      {% endif %}
    </div>
  </div>
  

  

</div>

  {% block javascripts %}
  <script src="https://cdn.jsdelivr.net/npm/chart.js@3.3.2/dist/chart.min.js"></script>
  <script src="{% static 'ID_system/js/createAttendanceChart.js' %}"></script>
  <script>
    var dates = {{ dates|safe }};
    var attendanceCounts = {{ attendance_counts }};
    createAttendanceChart(dates, attendanceCounts);
  </script>

  {% endblock javascripts %}
    
{% include 'base/footer.html' %}

{% endblock %}

university/templates/university/cafe/coupon.html
<div class="d-flex justify-content-between align-items-center">
  <h1>Coupons</h1>
  <a href="{% url 'university:add-coupon' %}" class="btn btn-primary">Add Coupon</a>
</div>
  <div class="accordion" id="couponAccordion">
  {% for coupon in coupons %}
    <div class="accordion-item">
      <h2 class="accordion-header" id="coupon{{ coupon.id }}Header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#coupon{{ coupon.id }}Collapse" aria-expanded="false" aria-controls="coupon{{ coupon.id }}Collapse">
          {{ coupon.coupon_type }}
        </button>
      </h2>
      <div id="coupon{{ coupon.id }}Collapse" class="accordion-collapse collapse" aria-labelledby="coupon{{ coupon.id }}Header" data-bs-parent="#couponAccordion">
        <div class="accordion-body">
          <p>{{ coupon.description }}</p>
          <p>End date: {{ coupon.expiration_date }}</p>
          <a href="{% url 'university:coupon-detail' coupon.id %}" class="btn btn-primary">View details</a>
          <a href="{% url 'university:delete-coupon' coupon.id %}?next_page={{current_url}}" class="btn btn-danger">Delete</a>
        </div>
      </div>
    </div>
  {% empty %}
    <p>No coupons found.</p>
  {% endfor %}
  </div>

university/templates/university/cafe/coupon_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Cafe Form{% endblock %}

{% block content %}
{% include 'base/header.html' with active_tab='cafe' %}
{% include 'base/side_bar.html' with active_tab='cafe' %}

<div class="container" id="main">
  <h1>Coupons</h1>
  <div class="accordion" id="couponAccordion">
  {% for coupon in coupons %}
    <div class="accordion-item">
      <h2 class="accordion-header" id="coupon{{ coupon.id }}Header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#coupon{{ coupon.id }}Collapse" aria-expanded="false" aria-controls="coupon{{ coupon.id }}Collapse">
          {{ coupon.coupon_type }}
        </button>
      </h2>
      <div id="coupon{{ coupon.id }}Collapse" class="accordion-collapse collapse" aria-labelledby="coupon{{ coupon.id }}Header" data-bs-parent="#couponAccordion">
        <div class="accordion-body">
          <p>{{ coupon.description }}</p>
          <p>End date: {{ coupon.expiration_date }}</p>
          <a href="{% url 'university:coupon-detail' coupon.id %}" class="btn btn-primary">View details</a>
        </div>
      </div>
    </div>
  {% empty %}
    <p>No coupons found.</p>
  {% endfor %}
  </div>
  {% if is_paginated %}
    <nav aria-label="Coupon navigation">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo; Previous</a></li>
        {% else %}
          <li class="page-item disabled"><span class="page-link">&laquo; Previous</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next &raquo;</a></li>
        {% else %}
          <li class="page-item disabled"><span class="pagelink">&raquo; Next</span></li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}
  </div>

{% include 'base/footer.html' %}

{% endblock %}

university/templates/university/cafe/student_list.html
<div class="container">
  <div class="col d-md-flex justify-content-md-end">
    <a href="{% url 'university:cafe-form' %}" class="btn btn-primary mx-3">Add Meal Service</a>
  </div>
  <div class="container text-center">
    <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
      <div class="card-body">
        <h5 class="card-title text-center">List of {{ meal_time|capfirst }} meal Period</h5>
      </div>
    </div>
  </div>
  
  <form class="form-inline float-right" method="get" action="">
    <div class="input-group">
      <a href="{% url 'university:cafe-manager' %}" class="btn btn-outline-primary">View Current Meal</a>
      <input type="search" class="form-control rounded" name="query" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
      <select class="select" data-mdb-filter="true" name="meal_time">
        <option value="all">All</option>
        {% for meal_period in meal_periods %}       
          <option value="{{ meal_period.meal_period }}">{{ meal_period.meal_period }}</option>
        {% endfor %}
      </select>
      <button type="submit" class="btn btn-outline-primary mr-2">search</button>
    </div>
  </form>

  <div class="table-responsive">
    <table class="table m-3">
      <thead class="thead-light">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Stdent Name</th>
          <th scope="col">Student ID</th>
          <th class="d-none d-md-table-cell" scope="col">Meal</th>
          <th class="d-none d-md-table-cell" scope="col" >Meal Period</th>
          <th scope="col">Eat</th>
          <th scope="col">Special</th>
          <th scope="col"></th>

        </tr>
      </thead>
      <tbody>
        {% for service in cafe_services %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href='{% url "university:cafe-student-detail" service.student.student_id %}' class="text-decoration-none">{{ service.student.full_name }}</a></td>
            <td>{{ service.student.student_id }}</td>
            <td class="d-none d-md-table-cell">{{ service.meal.meal_period }}</td>
            <td class="d-none d-md-table-cell">{{ service.meal.time }}</td> 
            <td>{% if service.has_eaten %}
                  Yes
                {% else %}
                  No
                {% endif %}
            </td>
            <td>{% if service.special %}
                  Yes
                {% else %}
                  No
                {% endif %}
            </td>
            <td>
              {% if not service.has_eaten %}
                <a class='btn btn-small btn-danger py-0' href='{% url "university:eat-meal" service.id %}'>Eat</a>
              {% endif %}
            </td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="3">No Student found.</td>
          </tr>
        {% endfor %}
        
      </tbody>
    </table>
    {% include 'base/pagination.html' with page_obj=cafe_services %}
  </div>

</div>