API/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('auth/', views.login),
    path('students/', views.getAllStudent),
    path('student/<str:id>', views.getStudent, name='student'),
    #     path('address/', views.getAddress, name='address'),
    #     path('devices/', views.getDevice, name='devices'),
    path('meal/', views.getMeal, name='meal'),
    #     path('cafe_attendance/', views.getCafeAttendance, name='cafe_attendance'),
    path('cafe_attendance/',
         views.getCafeAttendance, name='cafe_attendance_update'),
    path('add_disciplinary_record/', views.createDisciplinaryRecord,
         name='add_disciplinary_record'),

]

ID_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('university.urls', namespace='university')),
    path('api/', include('API.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

university/urls.py
from django.urls import path
from . import views

app_name = 'university'
urlpatterns = [
     path('', views.index, name='home'),
     path('about/', views.about_us, name='about_us'),
     path('staff/password/', views.ChangePasswordView.as_view(), name='password_change'),
     path('staff/<int:pk>', views.staff_update, name='staff_update'),
     path('staffs/registor/', views.create_staff, name='register-staff'),
     path('view_card/', views.view_scan, name='view-card'),
     path('view_card/<str:student_id>/', views.view_card, name='view-id'),
     path('login/', views.loginPage, name='login'),
     path("logout/", views.LogoutView.as_view(), name="logout"),


     # Student registration and QR code generation module
     path('student/registor/', views.student_form, name='register-student'),
     path('students/', views.students_list, name='list-students'),
     path('student_profile/<str:student_id>',
          views.student_profile, name='student-profile'),
     path('student_profile/update/<str:student_id>',
          views.update_student_profile, name='student-profile-update'),
     path('student_profile/add_device/<str:student_id>',
          views.add_device, name='add-device'),
     path('staffs/add/uni_info/', views.university_form,
          name='add-university-info'),
     path('staffs/list/uni_info/', views.department_list,
          name='department-list'),


     # Cafeteria service module
     path('cafe/', views.cafe_maneger, name='cafe-manager'),
     path('cafe/form/', views.cafe_form, name='cafe-form'),
     path('cafe/eat/<str:pk>', views.eat_meal, name='eat-meal'),
     path('cafe/coupon/add/', views.add_coupon, name='add-coupon'),
     path('cafe/coupon/list/', views.CouponListView.as_view(), name='list-coupon'),
     path('cafe/coupon/<int:coupon_id>/',
          views.coupon_detail, name='coupon-detail'),
     path('cafe/coupon/delete/<int:coupon_id>/',
          views.CouponDeleteView.as_view(), name='delete-coupon'),
     path('cafe/add_coupon_to_students/', views.add_coupon_to_students,
          name='add-coupon-to-students'),
     path('cafe/student/detail/<str:student_id>/', views.cafe_user_detail,
          name='cafe-student-detail'),


     # Library module
     path('library/', views.LibraryListView.as_view(), name='library-manager'),
     path('library/<int:pk>/return/', views.book_return, name='library-return'),
     path('library/add_book/', views.add_book, name='add-book'),
     path('library/students/', views.library_student_list,
          name='student-book-rent'),
     path('library/book-rental/<str:student_id>/',
          views.book_rental_page, name='book-rental-page'),
     path('library/book-rental/<str:student_id>/<int:book_id>/rent/',
          views.rent_book, name='rent-book'),

     # Disciplinary recording module
     path('disciplin/',
          views.DisStudentListView.as_view(), name='disciplin-student-list'),
     path('disciplin/record/<str:student_id>/',
          views.add_disciplinary_record, name='disciplin-form'),
     path('disciplin/list/<str:student_id>/',
          views.disciplinary_records, name='disciplin-list'),
     path('disciplin/recored/<int:record_id>/',
          views.disciplinary_record, name='disciplin-recored-detail'),


]

university/views.py
from .models import Student, Department
from django.shortcuts import render
from django.db.models import F, Q, Value
from django.db.models.functions import Concat
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View, CreateView, ListView
from django.contrib import messages
from django.utils import timezone
from django.db.models import Count, Q
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.db.models.functions import Trunc
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView

from .models import *
from .forms import *
from .decorators import role_required


def paginate(request, data, per_page=10):
    paginator = Paginator(data, per_page)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    context = {
        'title': 'Welcome to University of Gondar!',
        'subtitle': 'Learn more about our services',
        'services': [
            {'title': 'Undergraduate Programs',
                'description': 'We offer a wide range of undergraduate programs in various fields of study, including: Accounting, Agriculture, Architecture, Business Administration, Civil Engineering, Computer Science, Education, Environmental Science, Law, Medicine, Nursing, Pharmacy, Public Health, and more.'},
            {'title': 'Graduate Programs',
                'description': 'We offer several graduate programs, including master\'s and doctoral degrees in various fields of study, including: Accounting, Agriculture, Architecture, Business Administration, Civil Engineering, Computer Science, Education, Environmental Science, Law, Medicine, Nursing, Pharmacy, Public Health, and more.'},
            {'title': 'Research',
                'description': 'We conduct research in various areas, including health, agriculture, technology, social sciences, and humanities.'},
            {'title': 'Community Engagement',
                'description': 'We work closely with local communities to address social and economic challenges, including health, education, and poverty reduction.'},
            {'title': 'Continuing Education',
                'description': 'We offer continuing education programs and professional development courses for working professionals and lifelong learners.'},
            {'title': 'International Programs',
                'description': 'We offer international programs and exchange opportunities for students and faculty to study and collaborate with partner institutions around the world.'},
        ],
        'contact': {
            'email': 'info@example.com',
            'phone': '+1 (555) 123-4567',
            'address': '123 Main St, Anytown USA',
        },
        'university': {
            'name': 'University of Gondar',
            'location': 'Gondar, Ethiopia',
            'description': 'The University of Gondar is a public research university located in the historic city of Gondar in Ethiopia. It was established in 1954 and has since grown into one of the largest and most prestigious universities in the country.',
            'photo': 'https://example.com/university-of-gondar.jpg',
        },
    }
    return render(request, 'index.html', context)


def about_us(request):
    return render(request, 'base/about.html')

# Staff
@login_required
@role_required(['REGISTRAR'])
def create_staff(request):

    
    if request.method == 'POST':
        form = StaffRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            # Handle successful form submission
            return redirect('university:home')
    else:
        form = StaffRegistrationForm()

    return render(request, 'university/staff/staff_register.html', {'form': form})


def loginPage(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, username +
                             ' Welcome To UoG Student ID management System')
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            else:
                if user.is_superuser:
                    return redirect('university:list-students')
                if user.role == 'CAFE_STAFF':
                    return redirect('university:cafe-manager')
                if user.role in ('SECURITY','PROCTOR'):
                    return redirect('university:disciplin-student-list')
                if user.role == 'LIBRARIAN':
                    return redirect('university:library-manager')
            return redirect('university:list-students')

        else:
            messages.error(request, 'username or password is incorrect')

    return render(request, 'university/login.html')


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('university:login')

def staff_update(request, user_id):
    staff = get_object_or_404(Staff, pk=user_id)
    form = StaffChangeForm(instance=staff)

    if request.method == "POST":
        form = StaffChangeForm(request.POST, instance=staff)

        if form.is_valid():
            user = form.save()
            messages.success(request, (f"Profile updated for {user.username}"))
            return redirect("Staff:staff_detail", user.id)
        else:
            messages.error(request, ("please fix the errors"))

    context = {"form": form, "staff": staff}

    return render(request, "staff/update_profile.html", context)


class ChangePasswordView(PasswordChangeView):
    success_url = reverse_lazy('password_change_done')
    template_name = 'university/staff/change_password.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

@login_required
def view_card(request, student_id):

    context = {
        'student': Student.objects.get(student_id=student_id),
        'current_url': request.build_absolute_uri(),
    }

    return render(request, 'university/view_id.html', context)


@login_required
def view_scan(request):
    if request.method == 'GET':
        student_id = request.GET.get('student_id')
    if student_id is None:
        return HttpResponse("Student ID is Invalid")
    else:
        student_id = student_id.strip()
        context = {
            'student': Student.objects.get(student_id=student_id),
            'current_url': request.build_absolute_uri(),
        }

        return render(request, 'university/view_id.html', context)


# Student registration and QR code generation module
@login_required
@role_required(['REGISTRAR'])
def student_form(request):
    if request.method == 'POST':
        address_form = AddressForm(request.POST)

        emergency_form = EmergencyContactForm(request.POST)

        student_form = StudentForm(request.POST, request.FILES)

        if address_form.is_valid() and student_form.is_valid() and emergency_form.is_valid():
            address = address_form.save()

            emergency = emergency_form.save()
            student = student_form.save(commit=False)
            student.address = address
            student.emergency = emergency
            student.save()

            return redirect('university:list-students')
    else:
        address_form = AddressForm()

        emergency_form = EmergencyContactForm()

        student_form = StudentForm()

    context = {
        'address_form': address_form,
        'student_form': student_form,
        'emergency_form': emergency_form,
        'action': 'Register',

        'current_url': request.build_absolute_uri(),
    }

    return render(request, 'university/student_form.html', context)


@login_required
@role_required(['REGISTRAR'])
def add_device(request, student_id):
    # Get the student object based on the id passed in the URL
    student = Student.objects.get(id=student_id)

    # Check if the request method is POST
    if request.method == 'POST':
        # Create a DeviceForm instance with the POST data
        form = DeviceForm(request.POST)

        # Check if the form is valid
        if form.is_valid():
            # Create a new device object with the student and form data
            device = form.save(commit=False)
            device.student = student
            device.save()

            # Redirect the user to the student detail page
            return redirect('university:student-profile', student_id=student.student_id)

    # If the request method is not POST, create an empty DeviceForm instance
    else:
        form = DeviceForm()

    # Render the add device form template with the DeviceForm instance and student object
    return render(request, 'university/registerar/add_device.html', {'form': form, 'student': student})


@login_required
@role_required(['REGISTRAR'])
def student_profile(request, student_id):
    student = Student.objects.get(student_id=student_id)
    address = Student.address
    emergency = Student.emergency
    library = Library.objects.filter(student=student)

    devices = student.devices.all()
    disciplinary_records = DisciplinaryRecord.objects.filter(student=student)

    # Get the search query from the request GET parameters
    search_query = request.GET.get('q')
    if search_query:

university/templates/base/about.html
{% extends 'base/base.html' %}

{% block title %}About Us{% endblock %}

{% block content %}
  {% include 'base/header.html' with active_tab='about' %}
  <div class="container my-5">
    <h1 class="text-center mb-4">About Us</h1>
    <hr>
    <div class="row">
      <div class="col-md-6 mb-3 mb-md-0">
        <h3>Our Mission</h3>
        <p>We are committed to providing the best QR code-based student ID system to schools and universities around the world. Our mission is to help improve the efficiency and accuracy of student identification while also enhancing campus security.</p>
      </div>
      <div class="col-md-6">
        <h3>Our Team</h3>
        <ul class="list-unstyled mb-0">
          <li><strong>Muse Muliye:</strong> Developer</li>
          <li><strong>Smachew Fekad:</strong> Developer</li>
          <li><strong>Solomon Eshete:</strong> Developer</li>
          <li><strong>Tiruneh Ambachew:</strong> Developer</li>
          <li><strong>Mr. HabtamuA.:</strong> Advisor</li>
        </ul>
      </div>
    </div>
  </div>
  {% include 'base/footer.html' %}
{% endblock %}

university/templates/base/base.html
{% load static %}
{% load fontawesome_5 %}
{% fontawesome_5_static %} 
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Default Title{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'bootstrap-5.3/css/bootstrap.min.css' %}">

  {% block style %}{% endblock style %}
</head>
<body class='bg-dark-mode'>
  {% for message in messages %}
    {% if message.tags == 'error' %}
    <div class='alert alert-danger alert-dismissable'>
      {{  message }}
    </div>
    {% else %}
    <div class='alert alert-success alert-dismissable'>
      {{  message }}
    </div>
    {% endif %}
  {% endfor %}
  {% block content %}
  {% endblock %}
  
</body>
{% block javascripts %}{% endblock javascripts %}
<script src="{% static 'bootstrap-5.3/js/bootstrap.bundle.min.js' %}"></script>
</html>

university/templates/base/footer.html
<style>
  body {
    min-height: 100vh;
    position: relative;
    padding-bottom: 60px; /* Height of the footer */
  }

  .footer {
    position: absolute;
    bottom: 0;
    width: 100%;
    height: 60px;
    background-color: #f5f5f5;
  }
</style>

<footer class="footer bg-light py-3">
  <div class="container-fluid bg-light">
    <div class="row">
      <div class="col-md-4 mb-3 mb-md-0">
        <h6>About the Project</h6>
        <p class="mb-0" style="font-size: 14px;">This is a thesis project for a QR code-based student ID system.</p>
      </div>
      <div class="col-md-4 mb-3 mb-md-0">
        <h6>Developers</h6>
        <ul class="list-unstyled mb-0" style="font-size: 14px;">
          <li>Muse Muliye</li>
          <li>Smachew Fekad</li>
          <li>Solomon Eshete</li>
          <li>Tiruneh Ambachew</li>
        </ul>
      </div>
      <div class="col-md-4 mb-3">
        <h6>Advisor</h6>
        <p class="mb-0" style="font-size: 14px;">Mr. Habtamu A.</p>
      </div>
    </div>
    <hr class="my-3">
    <p class="mb-0 text-center">&copy; 2023. All rights reserved.</p>
  </div>
</footer>

university/templates/base/header.html
{% load custom_filters %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand {% if active_tab == 'home' %} text-primary {% endif %}" href="{% url 'university:home' %}"><i class="fas fa-id-card"></i> UoG ID_system</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
              {% with user=request.user %}
                  {% if user.is_superuser or user|has_user_role:"is_registerar" %}
                      <li class="nav-item"><a class="nav-link{% if active_tab == 'staffs' %} active text-primary {% endif %}" href="{% url 'university:list-students' %}">Staffs</a></li>
                  {% endif %}
                  {% if user.is_superuser or user|has_user_role:"is_cafe_staff" %}
                      <li class="nav-item"><a class="nav-link{% if active_tab == 'cafe' %} active text-primary {% endif %}" href="{% url 'university:cafe-manager' %}">Cafeteria</a></li>
                  {% endif %}
                  {% if user.is_superuser or user|has_user_role:"is_librarist" %}
                      <li class="nav-item"><a class="nav-link{% if active_tab == 'library' %} active text-primary {% endif %}" href="{% url 'university:library-manager' %}">Library</a></li>
                  {% endif %}
                  <li class="nav-item"><a class="nav-link{% if active_tab == 'disciplin' %} active text-primary {% endif %}" href="{% url 'university:disciplin-student-list' %}">Disciplinary</a></li>
                  <li class="nav-item">
                      <a class="nav-link{% if active_tab == 'about' %} active text-primary {% endif %}" href="{% url 'university:about_us' %}">About</a>
                  </li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'university:logout' %}">Logout <i class="fas fa-sign-out-alt"></i></a></li>
              {% endwith %}
          {% else %}
              <li class="nav-item"><a class="nav-link" href="{% url 'university:login' %}">Login</a></li>
          {% endif %}
      </ul>
  </div>
  </div>
</nav>

university/templates/base/pagination.html
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <!-- table content -->
      </table>
      <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
          <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
          {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
          {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </div>
</div>

university/templates/base/side_bar.html
<style>
  .sidebar {
    height: 100%; /* 100% Full-height */
    width: 0; /* 0 width - change this with JavaScript */
    position: fixed; /* Stay in place */
    z-index: 1; /* Stay on top */
    top: 0;
    left: 0;
    background-color: #111; /* Black*/
    overflow-x: hidden; /* Disable horizontal scroll */
    padding-top: 60px; /* Place content 60px from the top */
    transition: 0.5s; /* 0.5 second transition effect to slide in the sidebar */
  }
  
  /* The sidebar links */
  .sidebar a {
    padding: 8px 8px 8px 32px;
    text-decoration: none;
    font-size: 25px;
    color: #818181;
    display: block;
    transition: 0.3s;
  }
  
  /* When you mouse over the navigation links, change their color */
  .sidebar a:hover {
    color: #f1f1f1;
  }
  
  /* Position and style the close button (top right corner) */
  .sidebar .closebtn {
    position: absolute;
    top: 0;
    right: 25px;
    font-size: 36px;
    margin-left: 50px;
  }
  
  /* The button used to open the sidebar */
  .openbtn {
    font-size: 20px;
    cursor: pointer;
    background-color: #111;
    color: white;
    padding: 10px 15px;
    border: none;
  }
  
  .openbtn:hover {
    background-color: #444;
  }
  
  /* Style page content - use this if you want to push the page content to the right when you open the side navigation */
  #main {
    transition: margin-left .5s; /* If you want a transition effect */
  }
  
  /* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
  @media screen and (max-height: 450px) {
    .sidebar {padding-top: 15px;}
    .sidebar a {font-size: 18px;}
  }
</style>
<div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  
  {% if active_tab == 'staffs' %}
    <a href='{% url 'university:list-students' %}'>List Students</a>
    <a href='{% url 'university:register-student' %}'>Register Student</a>
    <a href='{% url 'university:register-staff' %}'>Create Staff Account</a>
    <a href='{% url 'university:add-university-info' %}'>Add Department</a>
    <a href='{% url 'university:department-list' %}'>Show Departments</a>

  {% elif active_tab == 'cafe' %}
    <p>Cafe</p>
    <a href='{% url 'university:cafe-manager' %}'>Home</a>
    <a href='{% url 'university:cafe-form' %}'>Form</a>
    <a href='{% url 'university:add-coupon' %}'>New Coupon</a>
    <a href='{% url 'university:add-coupon-to-students' %}'>Add Coupon for Students</a>

  {% elif active_tab == 'library' %}
    <p>Library</p>
    <a href='{% url 'university:library-manager' %}'>Home</a>
    <a href='{% url 'university:student-book-rent' %}'>Book Rent</a>
    <a href='{% url 'university:add-book' %}'>New Book</a>
  {% endif %}
</div>

<div>
  <button class="openbtn" id="openNav" onclick="openNav()">&#9776;</button>
</div>

<script>
  /* Set the width of the sidebar to 250px and the left margin of the page content to 250px */
function openNav() {
  document.getElementById("main").style.marginLeft = "15%";
  document.getElementById("mySidebar").style.width = "15%";
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("openNav").style.display = 'none';
}

/* Set the width of the sidebar to 0 and the left margin of the page content to 0 */
function closeNav() {
  document.getElementById("main").style.marginLeft = "13%";
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("openNav").style.display = "inline-block";
}

</script>