API/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('auth/', views.login),
    path('students/', views.getAllStudent),
    path('student/<str:id>', views.getStudent, name='student'),
    #     path('address/', views.getAddress, name='address'),
    #     path('devices/', views.getDevice, name='devices'),
    path('meal/', views.getMeal, name='meal'),
    #     path('cafe_attendance/', views.getCafeAttendance, name='cafe_attendance'),
    path('cafe_attendance/',
         views.getCafeAttendance, name='cafe_attendance_update'),
    path('add_disciplinary_record/', views.createDisciplinaryRecord,
         name='add_disciplinary_record'),

]

ID_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('university.urls', namespace='university')),
    path('api/', include('API.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

university/urls.py
from django.urls import path
from . import views

app_name = 'university'
urlpatterns = [
     path('', views.index, name='home'),
     path('about/', views.about_us, name='about_us'),
     path('staff/password/', views.ChangePasswordView.as_view(), name='password_change'),
     path('staff/<int:pk>', views.staff_update, name='staff_update'),
     path('staffs/registor/', views.create_staff, name='register-staff'),
     path('view_card/', views.view_scan, name='view-card'),
     path('view_card/<str:student_id>/', views.view_card, name='view-id'),
     path('login/', views.loginPage, name='login'),
     path("logout/", views.LogoutView.as_view(), name="logout"),


     # Student registration and QR code generation module
     path('student/registor/', views.student_form, name='register-student'),
     path('students/', views.students_list, name='list-students'),
     path('student_profile/<str:student_id>',
          views.student_profile, name='student-profile'),
     path('student_profile/update/<str:student_id>',
          views.update_student_profile, name='student-profile-update'),
     path('student_profile/add_device/<str:student_id>',
          views.add_device, name='add-device'),
     path('staffs/add/uni_info/', views.university_form,
          name='add-university-info'),
     path('staffs/list/uni_info/', views.department_list,
          name='department-list'),


     # Cafeteria service module
     path('cafe/', views.cafe_maneger, name='cafe-manager'),
     path('cafe/form/', views.cafe_form, name='cafe-form'),
     path('cafe/eat/<str:pk>', views.eat_meal, name='eat-meal'),
     path('cafe/coupon/add/', views.add_coupon, name='add-coupon'),
     path('cafe/coupon/list/', views.CouponListView.as_view(), name='list-coupon'),
     path('cafe/coupon/<int:coupon_id>/',
          views.coupon_detail, name='coupon-detail'),
     path('cafe/coupon/delete/<int:coupon_id>/',
          views.CouponDeleteView.as_view(), name='delete-coupon'),
     path('cafe/add_coupon_to_students/', views.add_coupon_to_students,
          name='add-coupon-to-students'),
     path('cafe/student/detail/<str:student_id>/', views.cafe_user_detail,
          name='cafe-student-detail'),


     # Library module
     path('library/', views.LibraryListView.as_view(), name='library-manager'),
     path('library/<int:pk>/return/', views.book_return, name='library-return'),
     path('library/add_book/', views.add_book, name='add-book'),
     path('library/students/', views.library_student_list,
          name='student-book-rent'),
     path('library/book-rental/<str:student_id>/',
          views.book_rental_page, name='book-rental-page'),
     path('library/book-rental/<str:student_id>/<int:book_id>/rent/',
          views.rent_book, name='rent-book'),

     # Disciplinary recording module
     path('disciplin/',
          views.DisStudentListView.as_view(), name='disciplin-student-list'),
     path('disciplin/record/<str:student_id>/',
          views.add_disciplinary_record, name='disciplin-form'),
     path('disciplin/list/<str:student_id>/',
          views.disciplinary_records, name='disciplin-list'),
     path('disciplin/recored/<int:record_id>/',
          views.disciplinary_record, name='disciplin-recored-detail'),


]

university/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.core import validators
import uuid
import qrcode
import datetime

from .utils import generate_qr_code
from .validators import *


def get_student_photo_filepath(self, image):
    return f"students/{self.full_name}/photo/{self.full_name}.png"


def get_default_photo():
    return "profile_images/default_profile_pic.png"


def get_student_qr_code_filepath(self, image):
    return f"student/{self.full_name}/qr_code/{self.full_name}.png"


def get_profile_image_filepath(self, image):
    return f"staffs/{self.username}/profile_images/{self.username}_profile_image.png"


def get_default_profile_image():
    return "profile_images/default_profile_pic.png"


class Staff(AbstractUser):
    ROLE = (
        ("REGISTRAR", "Registrar"),
        ("LIBRARIAN", "Librarian"),
        ("PROCTOR", "Proctor"),
        ("SECURITY", "Security"),
        ("CAFE_STAFF", "Cafe Staff"),
        ("ADMIN", "Admin"),
    )
    full_name_am = models.CharField(
        "ሙሉ ስም", max_length=200, validators=[validate_amharic], null=True, blank=True
    )
    phone_number = models.CharField(
        max_length=20,
        validators=[validate_ethiopian_phone_number],
        null=True,
        blank=True,
    )
    photo = models.ImageField(
        "profile picture",
        upload_to=get_profile_image_filepath,
        default=get_default_profile_image,
        blank=True,
    )
    email = models.EmailField("email address", unique=True, null=True, blank=True)
    role = models.CharField("Role", max_length=10, choices=ROLE)


    # def get_absolute_url(self):
    #     return reverse("staff_detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        if self.pk is None and self.is_superuser:
            self.role = "ADMIN"
        if self.role in ("ADMIN", "REGISTRAR"):
            self.is_superuser = True
        if self.role not in ("ADMIN", "REGISTRAR"):
            self.is_superuser = False
        if self.photo is None:
            self.photo = get_default_photo

        super().save(*args, **kwargs)


User = get_user_model()


class Address(models.Model):
    telephone_phone = models.CharField(max_length=20, validators=[
                                       validate_ethiopian_phone_number], null=True, blank=True)
    email = models.EmailField()
    country = models.CharField(max_length=150)
    region = models.CharField(max_length=150)
    state = models.CharField(max_length=150)

    def __str__(self):
        return self.country + ', ' + self.region + ', ' + self.state


class EmergencyContact(models.Model):
    name = models.CharField(max_length=255, verbose_name="Full Name")
    name_am = models.CharField(
        max_length=255, verbose_name="ሙሉ ስም", validators=[validate_amharic])
    relationship = models.CharField(
        max_length=255, verbose_name="relationship")
    relationship_am = models.CharField(
        max_length=255, verbose_name="ዝምድና", validators=[validate_amharic])
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    country = models.CharField(max_length=150, null=True, blank=True)
    region = models.CharField(max_length=150, null=True, blank=True)
    state = models.CharField(max_length=150, null=True, blank=True)

    def __str__(self):
        return self.name

    def address(self):
        return self.country + ', ' + self.region + ', ' + self.state


class Coupon(models.Model):
    coupon_type = models.CharField(max_length=50)
    discription = models.TextField(max_length=100, null=True, blank=True)
    expiration_date = models.DateField(validators=[validators.MinValueValidator(
        limit_value=datetime.datetime.today().date(), message="Expiration date cannot be earlier than today's date.")])

    def __str__(self):
        return f"{self.coupon_type} - {self.expiration_date}"


class Campus(models.Model):
    name = models.CharField(max_length=255, verbose_name='Campus Name')
    name_am = models.CharField(
        max_length=255, verbose_name='የካምፓስ ስም', validators=[validate_amharic])
    address = models.ForeignKey(Address, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Field(models.Model):
    name = models.CharField(max_length=255, verbose_name='Field Name')
    name_am = models.CharField(
        max_length=255, verbose_name='ፊልድ', validators=[validate_amharic])
    campus = models.ForeignKey(Campus, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Department(models.Model):
    name = models.CharField(max_length=255, verbose_name='Department Name')
    name_am = models.CharField(
        max_length=255, verbose_name='የትምህርት ክፍል', validators=[validate_amharic])
    field = models.ForeignKey(Field, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Student(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    # Fields for student information
    first_name = models.CharField(max_length=100, verbose_name='First Name')
    first_name_am = models.CharField(
        max_length=100, verbose_name='ስም', validators=[validate_amharic])
    last_name = models.CharField(max_length=100, verbose_name='Last Name')
    last_name_am = models.CharField(
        max_length=100, verbose_name='የአባት ስም', validators=[validate_amharic])
    student_id = models.CharField(max_length=20, unique=True)
    photo = models.ImageField(upload_to='photos/', default='img/p_pic.png')
    qr_code = models.ImageField(upload_to='qr_codes')
    date_of_birth = models.DateField(validators=[validate_birth_date])
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    government_id_number = models.CharField(max_length=50)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    emergency = models.ForeignKey(
        EmergencyContact, on_delete=models.CASCADE)
    registration_date = models.DateTimeField(auto_now_add=True)
    address = models.ForeignKey(
        Address, on_delete=models.CASCADE, default=None, null=True, blank=True)
    financial_aid = models.BooleanField()
    is_cafe_user = models.BooleanField(default=True)
    is_student_associative = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    coupon = models.ManyToManyField(
        Coupon, verbose_name="coupon", blank=True,  related_name='students')
    year = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.student_id})"

    def age(self):
        today = datetime.date.today()
        return today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def save(self, *args, **kwargs):
        # Generate unique student ID and QR code when student is registered
        if not self.pk:

            # Generate UUID
            unique_id = uuid.uuid4().hex[:5].upper()

            # Get 2 digites of year
            current_year = datetime.datetime.now().year
            last_two_digits = current_year % 100
            year = str(last_two_digits)[-2:]

            # Set student ID in the format "UoG/XXXXX/year"
            self.student_id = f"UoG|{unique_id}|{year}"

            if not self.qr_code:
                self.qr_code = generate_qr_code(self.student_id)
        super().save(*args, **kwargs)


class Device(models.Model):
    student = models.ForeignKey(
        Student, on_delete=models.CASCADE, related_name='devices')
    device_type = models.CharField(max_length=80)
    device_model = models.CharField(max_length=100)
    serial_number = models.CharField(max_length=17)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.serial_number} ({self.student})"


class SpecialMealPeriod(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Meal(models.Model):
    MEAL_PERIODS = (
        ('breakfast', 'Breakfast'),
        ('lunch', 'Lunch'),
        ('dinner', 'Dinner'),
        # Add special meal periods from the SpecialMealPeriod model
        *[(special_meal_period.name.lower(), special_meal_period.name.title()) for special_meal_period in SpecialMealPeriod.objects.all()]
    )

    meal_period = models.CharField(choices=MEAL_PERIODS, max_length=20)
    start_time = models.TimeField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return f'{self.get_meal_period_display()} - From {self.start_date} to {self.end_date}'.format(self.start_date, self.end_date)

    def time(self):
        return f'From {self.start_date} to {self.end_date}'.format(self.start_date, self.end_date)


class CafeAttendance(models.Model):
    student = models.ForeignKey(
        Student, on_delete=models.CASCADE, related_name='cafeatendance_set')
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    has_eaten = models.BooleanField(default=False)
    check_in_time = models.TimeField(null=True, blank=True)

    def __str__(self):
        return f'{self.student} - {self.meal} - {self.has_eaten}'

    def save(self, *args, **kwargs):
        if self.has_eaten:
            self.check_in_time = datetime.datetime.now().time()
        super().save(*args, **kwargs)


class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    isbn = models.CharField(max_length=13)

    def __str__(self):
        return f'{self.title} - {self.author}'


class Library(models.Model):

university/templates/university/student_profile.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}{{ student }} Profile {% endblock %}

{% block content %}
{% include 'base/header.html' with active_tab='staffs' %}

{% include 'base/side_bar.html' with active_tab='staffs' %}
<div class="container" id="main">
    <a href="{% url 'university:student-profile-update' student.student_id %}" class="btn btn-primary m-3 text-black">Update</a>
    <a href="{% url 'university:disciplin-list' student.student_id %}" class="btn btn-primary m-3 text-black">Show Disciplinary recoreds</a>
    <a href="{% url 'university:disciplin-form' student.student_id %}" class="btn btn-danger m-3 text-black">Add Disciplinary recored</a>

    <div class="row">
        <div class="col-md-12">
            <div class="card mb-3">
                <div class="card-body">
                    <h4 class="card-title">Personal Information</h4>
                    <div class="row">
                        <div class="col-md-4">
                            <img class="card-img-top" src="{{ student.photo.url }}" alt="Student Photo" style="max-width: 120%; height: auto;">
                        </div>
                        <div class="col-md-3">
                        <p class="card-text"><strong>Student ID:</strong> {{ student.student_id }}</p>
                        <p class="card-text"><strong>Date of Birth:</strong> {{ student.date_of_birth }}</p>
                        <p class="card-text"><strong>Gender:</strong> {{ student.get_gender_display }}</p>
                        <p class="card-text"><strong>Government ID Number:</strong> {{ student.government_id_number }}</p>
                        <p class="card-text"><strong>Address:</strong> {{ student.address }}</p>
                        </div>
                        <div class="col-md-3">
                            <p class="card-text"><strong>Age:</strong> {{ student.age }}</p>
                            <p class="card-text"><strong>Registered At:</strong> {{ student.registration_date }}</p>
                            <p class="card-text"><strong>Email:</strong><a class="text-decoration-none text-dark" href="mailto:{{ student.address.email }}"> {{ student.address.email }}</a> </p>
                            <p class="card-text"><strong>Phone Number:</strong><a class="text-decoration-none text-dark" href="tel:{{ student.address.phone_number }}">{{ student.address.phone_number }}</a> </p>
                        </div>
                        <div class="col-md-2">
                            <img class="card-img-top" src="{{ student.qr_code.url }}" alt="Student QR Code" style="max-width: 50%; height: auto;">
                        </div>
                    </div>
                </div>
            </div>
        </div>
   
    </div>

    <div class="row">
        <div class="col-md-4 ">
            <div class="card mb-4">
                <div class="card-body">
                    <h4 class="card-title">Academic Information</h4>
                    <p class="card-text"><strong>Department:</strong> {{ student.department }}</p>
                    <p class="card-text"><strong>Field:</strong> {{ student.field }}</p>
                    <p class="card-text"><strong>Registration Date:</strong> {{ student.registration_date }}</p>
                    <p class="card-text"><strong>Financial Aid:</strong> {% if student.financial_aid %}Yes{% else %}No{% endif %}</p>
                    <p class="card-text"><strong>Cafeteria User:</strong> {% if student.is_cafe_user %}Yes{% else %}No{% endif %}</p>
                    <p class="card-text"><strong>Student Associative:</strong> {% if student.is_student_associative %}Yes{% else %}No{% endif %}</p>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card mb-3">
                <div class="card-body">
                    <h4 class="card-title">Emergency Contacts</h4>
                    <p class="card-text"><strong>Name:</strong> {{ student.emergency.name }} ( {{ student.emergency.name_am }} )</p>
                    <p class="card-text"><strong>Relationship:</strong> {{ student.emergency.relationship }} ( {{ student.emergency.relationship_am }} )</p>
                    <p class="card-text"><strong>Phone Number:</strong> <a href="tel:{{ student.emergency.phone_number }}" class="text-decoration-none text-dark"> {{ student.emergency.phone_number }} </a></p>
                    <p class="card-text"><strong>Address:</strong> {{ student.emergency.address }}</p>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <h2>Devices</h2>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Type</th>
                  <th>Model</th>
                  <th>Serial number</th>
                  <th>Date registered</th>
                </tr>
              </thead>
              <tbody>
                {% for device in devices %}
                <tr>
                    <td>{{ device.device_type }}</td>
                    <td>{{ device.device_model }}</td>
                    <td>{{ device.serial_number }}</td>
                    <td>{{ device.date_added }}</td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="2">No devices found.</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <div class="d-md-flex justify-content-md-end mt-3">
              <a href="{% url 'university:add-device' student.id %}" class="btn btn-primary">Add Device</a>
            </div>
        </div>

    </div>
    

    <div class="card mb-3">
        <div class="no-gutters">
            <div class="card-body">
                <h5 class="card-subtitle mb-2 text-muted">Disciplinary Records</h5>
    
                <!-- Display the search form -->
                <form method="get" action="{% url 'university:student-profile' student.student_id %}">
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control" name="q" value="{{ search_query }}" placeholder="Search disciplinary records">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-outline-secondary">search</button>
                            </div>
                        </div>
                    </div>
                </form>
    
                <table class="table">
                    <thead class="thead-light">
                        <tr>
                            <th>Date</th>
                            <th>Reason</th>
                            <th>Staff</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if disciplinary_records %}
                            {% for record in disciplinary_records %}
                                <tr>
                                    <td><a class="text-decoration-none" href={% url 'university:disciplin-recored-detail' record.id %}>{{ record.reason|safe|truncatechars_html:50 }}</a></td>
                                    <td>{{ record.date }}</td>
                                    <td class="fit-text">{{ record.staff.get_full_name }}</td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td colspan="3">No disciplinary records found.</td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
    
                <!-- Display the pagination links -->
                {% include 'base/pagination.html' with page_obj=disciplinary_records %}
            </div>
        </div>
    </div>
</div>
{% include 'base/footer.html' %}

{% endblock %}

university/templates/university/students_list.html
{% extends 'base/base.html' %}
{% load static %} 

{% block title %}Students{% endblock %}

{% block content %}
  {% include 'base/header.html' with active_tab='staffs' %}
  {% include 'base/side_bar.html' with active_tab='staffs' %}
        
  <!--Section: Content-->
  <h3 class="fw-bolder">{{page_title}}</h3>
  <hr>
  <section class="py-3">
    <div class="container" id="main">
      <div class="row">
        <div class="col-lg-4 col-md-6 mb-4">
          <div class="card rounded-0 shadow-sm blur">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center">
                <div class="text-primary">
                  <i class="fas fa-user-graduate fa-2x"></i>
                </div>
                <div class="text-end">
                  <h5 class="fw-bold mb-0">{{ numberOfStudents }}</h5>
                  <p class="text-secondary mb-0">Total Students</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 mb-4">
          <div class="card rounded-0 shadow-sm blur">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center">
                <div class="text-primary">
                  <i class="fas fa-user-graduate fa-2x"></i>
                </div>
                <div class="text-end">
                  <h5 class="fw-bold mb-0">{{ numberOfMaleStudents }}</h5>
                  <p class="text-secondary mb-0">Male Students</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 mb-4">
          <div class="card rounded-0 shadow-sm blur">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center">
                <div class="text-primary">
                  <i class="fas fa-user-graduate fa-2x"></i>
                </div>
                <div class="text-end">
                  <h5 class="fw-bold mb-0">{{ numberOfFemaleStudents }}</h5>
                  <p class="text-secondary mb-0">Female Students</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="card rounded-0 shadow-sm blur">
        <div class="card-body">
          <div class="container-fluid">
            <div class="text-end mb-2">
              <a href="{% url 'university:register-student' %}" class="btn btn-primary btn-sm rounded-0 bg-gradient"><i class="fa fa-plus"></i> Add New Student</a>
            </div>
            <form method="get" class="mb-3">
              <div class="row">
                <div class="col-md-4 mb-3">
                  <label for="department-filter">Filter by Department:</label>
                  <select name="department" class="form-control" id="department-filter">
                    <option value="">All Departments</option>
                    {% for department in departments %}
                      <option value="{{ department.id }}" {% if department.id == selected_department.id %}selected{% endif %}>{{ department.name }}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="col-md-4 mb-3">
                  <label for="year-filter">Filter by Year:</label>
                  <select name="year" class="form-control" id="year-filter">
                    <option value="">All Years</option>
                    {% for year in years %}
                        <option value="{{ year }}">{{ year }}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="col-md-4 mb-3">
                  <label for="search-query">Search:</label>
                  <div class="input-group">
                    <input type="text" name="search_query" class="form-control" id="search-query" value="{% if search_query %}{{search_query}}{% endif %} ">
                    <button type="submit" class="btn btn-primary">Search</button>
                  </div>
                </div>
              </div>
            </form>
            <table class="table table-stripped table-bordered">
                <thead class="table-dark">
                  <tr>

                    <th>#</th>
                    <th><a class="text-decoration-none text-white" href="?sort_by=name{% if sort_by == 'name' %}&reverse=1{% endif %}">Name</a></th>
                    <th class="d-none d-sm-table-cell">Faculty</th>
                    <th><a class="text-decoration-none text-white" href="?sort_by=department{% if sort_by == 'department' %}&reverse=1{% endif %}">Department</a></th>
                    <th><a class="text-decoration-none text-white" href="?sort_by=year{% if sort_by == 'year' %}&reverse=1{% endif %}">Year</a></th>
                    <th><a class="text-decoration-none text-white" href="?sort_by=gender{% if sort_by == 'gender' %}&reverse=1{% endif %}">Gender</a></th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% if students %}
                    {% for student in students %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ student.full_name }}</td>
                        <td class="d-none d-sm-table-cell">{{ student.field.campus.name }}</td>
                        <td>{{ student.department.name }}</td>
                        {% if not year %}
                          <td class="d-none d-sm-table-cell">Registered in {{ student.registration_date|date:"Y" }}</td>
                        {% else %}
                          <td class="d-none d-sm-table-cell">{{ student.year }}</td>
                        {% endif %}
                        <td>{{ student.gender }}</td>
                        <td>
                          <div class="dropdown">
                            <button class="btn btn-light border bg-gradient btn-sm rounded-0 dropdown-toggle" type="button" id="stud{{student.pk}}" data-bs-toggle="dropdown" aria-expanded="false">
                              Action
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="studentIDD{{student.pk}}">
                              <li><a href="{% url 'university:student-profile-update' student.student_id %}" class="dropdown-item">Update</a></li>
                              <li><a href="{% url 'university:student-profile' student.student_id %}" class="dropdown-item">See Profile</a></li>
                              <li><a href="{% url 'university:disciplin-form' student.student_id %}" class="dropdown-item">Add Disciplinary Recored</a></li>
                              <li><a href="{% url 'university:view-id' student.student_id %}" class="dropdown-item">ID Card</a></li>
                            </ul>
                          </div>
                        </td>
                      </tr>
                    {% endfor %}
                  {% else %}
                    <tr>
                      <td colspan="6" class="text-center">No students found.</td>
                    </tr>
                  {% endif %}
                </tbody>
              </table>
              {% include 'base/pagination.html' with page_obj=students %}
              
          </div>
        </div>
      </div>
    </div>
  </section>
  
  {% comment %} <!-- Dashboard -->
  <section class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6 mb-4">
          <div class="card rounded-0 shadow-sm blur">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center">
                <div class="text-primary">
                  <i class="fas fa-list fa-2x"></i>
                </div>
                <div class="text-end">
                  <h5 class="fw-bold mb-0">List 1</h5>
                  <p class="text-secondary mb-0">Description of list 1</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-6 col-md-6 mb-4">
          <div class="card rounded-0 shadow-sm blur">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center">
                <div class="text-primary">
                  <i class="fas fa-list fa-2x"></i>
                </div>
                <div class="text-end">
                  <h5 class="fw-bold mb-0">List 2</h5>
                  <p class="text-secondary mb-0">Description of list 2</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section> {% endcomment %}
  
  {% include 'base/footer.html' %}
{% endblock %}

{% block scripts %}
  <script>
    function deleteStudent(studentId) {
      if (confirm("Are you sure you want to delete this student?")) {
        window.location.href = "{% url 'university:delete-student' %}?student_id=" + studentId;
      }
    }
  </script>
{% endblock %}